function tracker_job_features(output_feature_file_path, output_jaaba_folder_path, output_features_csv_folder_path, ...
                              input_video_file_name, input_tracking_file_name, calibration_file_name, ...
                              options)
    % Recompute the features file, csv feature files, and jaaba features.
    calibration = load_anonymous(calibration_file_name) ;
    core_tracker_compute_features(output_feature_file_path, output_features_csv_folder_path, output_jaaba_folder_path, ...
                                  input_video_file_name, input_tracking_file_name, calibration, ...
                                  options) ;
end
