function [center_dampen,angle_dampen,ang_dist_wt,max_jump,maxmajor,meanmajor,model_type,circular_arena,n_bg_std_thresh_low,iscalibfile] = ...
  fix_ReadAnnParams(annname)

[~,~,ext] = fileparts(annname);
iscalibfile = strcmpi(ext,'.mat');
if iscalibfile,
  calibd = load(annname);
  center_dampen = calibd.ann.center_dampen;
  angle_dampen = calibd.ann.angle_dampen;
  ang_dist_wt = calibd.ann.ang_dist_wt;
  max_jump = calibd.ann.max_jump;
  maxmajor = calibd.calib.params.max_major_axis/4;
  meanmajor = calibd.calib.params.mean_major_axis/4;
  model_type = calibd.ann.model_type;
  arena_radius = calibd.calib.r;
  arena_center_x = calibd.calib.centroids(2);
  arena_center_y = calibd.calib.centroids(1);
  do_set_circular_arena = calibd.calib.roi_type == 2;
  n_bg_std_thresh_low = calibd.ann.n_bg_std_thresh_low;
else
  [center_dampen,angle_dampen,ang_dist_wt,max_jump,maxmajor,meanmajor,...
    model_type,arena_radius,arena_center_x,arena_center_y,do_set_circular_arena,...
    n_bg_std_thresh_low] = ...%,vel_angle_wt] = ...
    read_ann(annname,'center_dampen','angle_dampen','ang_dist_wt','max_jump',...
    'maxmajor','meanmajor','model_type',...
    'arena_radius', 'arena_center_x', 'arena_center_y', 'do_set_circular_arena',...
    'n_bg_std_thresh_low');
  %,'maxmajor','meanmajor','velocity_angle_weight');
end
circular_arena = struct( ...
  'do_set_circular_arena', do_set_circular_arena, ...
  'arena_radius', arena_radius, ...
  'arena_center_x', arena_center_x, ...
  'arena_center_y', arena_center_y );
